### ISSUE TITLE
Fix bundle for this project

### ISSUE THREAD

**Issue by jiazhang0** [microsoft/confidential-ai#14]
It looks like there are some gaps now since this project was released.

I make some fixes to make sure this project can be successfully launched on Azure. Please check out https://github.com/jiazhang0/confidential-ai.git

Here are some details about the fixes.

- https://github.com/jiazhang0/confidential-ai/commit/7ac3a70bcf41d071daf2d03181d81dea856dcbdd: Contains the latest fixes in [confidential-sidecar-containers](https://github.com/microsoft/confidential-sidecar-containers) repo since Apr 6. The following commits are pretty useful: 
  - https://github.com/microsoft/confidential-sidecar-containers/commit/1d09a65c5cf018b767184cde1a0354206917bd33
  - https://github.com/microsoft/confidential-sidecar-containers/commit/45b7c1c82546709cde537289556b27d4a7879300#diff-06d30b9c5500714e87fb5fcac905ca3d436b4172bdb405d992a35fb96d83df6c

- https://github.com/jiazhang0/confidential-ai/commit/017fcf17c192e112ed2bec101252bb54f8166ec0 and https://github.com/jiazhang0/confidential-ai/commit/f89b831ad1174661ee4f48a664ac534ac7d8138f: fix build failures of proxy sidecar containers for both server and client side: `executor failed running [/bin/sh -c sudo apt-get install -y gettext]: exit code: 100`

- https://github.com/jiazhang0/confidential-ai/commit/347ffa4901c954a4bff8593b5ece85b58180458d: according to [the official doc](https://learn.microsoft.com/zh-cn/azure/container-instances/container-instances-tutorial-deploy-confidential-containers-cce-arm#create-an-aci-container-group-arm-template), the "sku" and "apiVersion" fields should be modified. In addition, the listening port for proxy sidecar should be 15006 matching up [the envoy config](https://github.com/microsoft/confidential-ai/blob/main/inference/server/proxy/proxy-config.yaml#L7).

- https://github.com/jiazhang0/confidential-ai/commit/eb48986f78b415892614f93113b76e5b0e71946c: give the exec permissions to the related scripts.

- https://github.com/jiazhang0/confidential-ai/commit/254e53a7e2bad1f45a2b00c2995f3f137ca7b1dc: The generation of ACI CCE policy is too long. Just cache the result so as to speed up the whole procedure.

- https://github.com/jiazhang0/confidential-ai/commit/aa9ea578a4d872d5765bddb7c48949e1a5b9276c: encfs sidecar requires the privilege to mount azure filesystem as FUSE.

- https://github.com/jiazhang0/confidential-ai/commit/d96eda147636d24e33410c1434b51ae3f89616bd: init container requires the privilege to set up iptables. In addition, it seems that there is no way to set the privilege for init container. So I have to run it as a normal container.

- https://github.com/jiazhang0/confidential-ai/commit/66ee7f3c8ba2c419cde4d38ceff12585c3d3d17a: A default iptables rule `aad-metadata` defined in nat table to access to the AKV metadata for AAD access token. So it must not unconditionally delete this default rule.

- https://github.com/jiazhang0/confidential-ai/commit/3c5a83c72706563ac001d08746dc3af2c8e2d8cf: The output of ACI CCE Policy digest contains a trailing newline character needed to be considered. Otherwise, the resulting digest will be truncated by 1 hex.

- https://github.com/jiazhang0/confidential-ai/commit/fb1faf8c2643fe6a04490f75e5529ecae477dec3: Just resolve this ACI deployment failure: `Please retry with a different resource request or in another location. Resource requested: '5' CPU '7.2' GB memory 'Linux' OS"`

- https://github.com/jiazhang0/confidential-ai/commit/e5dee78ee92587069a662a145b9a889cd923a74a and https://github.com/jiazhang0/confidential-ai/commit/95cf44268b3a95db1b1ab43291a264e5902d9c10: automatically do the role assignments with azure cli instead of web portal.

**Comment by kapilvgit** [comment]
@jiazhang0 please feel free to raise PRs against this repo.

**Comment by kapilvgit** [comment]
I have included your changes in a PR. Thanks for your support.
