### ISSUE TITLE
Deploy script failure 

### ISSUE THREAD

**Issue by iamgoutham** [microsoft/confidential-ai#9]
Below line in deployment/confidential-aci/deploy.sh  script fails as below.
az deployment group create --resource-group aci_inference_test --template-file arm-template.json --parameters @/tmp/aci-parameters.json
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"InvalidCcePolicy\",\r\n    \"message\": \"The CCE Policy cannot be left empty for Confidential Container Groups.\"\r\n  }\r\n}"}]}}
More Info:  az confcom acipolicygen -i /tmp/policy-in.json   command fails at 30% possibly because of insufficient memory
Reason:    az cli version 2.44 version
Fix:  Upgrading az cli to version 2.46 seems to fix the problem

**Comment by kapilvgit** [comment]
@iamgoutham apologies for the delayed response. Good to know that you found a fix.
